### ISSUE TITLE
form elements inside search result list

### ISSUE THREAD

**Issue by dasnovum** [innoq/simplete.obsolete#10]
Forms inside search results are not possible. The browser deletes nested forms.

```
<li data-value="info.pdf">
    <tt>info.pdf</tt>
    <small>PDF, 249 kB</small>
    <form action="http://google.com" method="get">
        <input name="q">
        <input type="submit">
    </form>
</li>
<li data-value="index.html">
    <tt>index.html</tt>
    <small>HTML, 43 kB</small>
    <form action="http://google.com" method="get">
        <input name="q">
        <input type="submit">
    </form>
</li>
```

**Comment by FND** [comment]
As discussed elsewhere, that's because HTML doesn't allow nesting forms. Since Simplete inserts results into the DOM right next to the respective input field (mostly because that makes abspos styling easy), those results end up being part of the form. So while it seems a bit unusual to provide forms within the list of results, there's no reason to disallow that.

db3f0552ed6be4caad5bc933dc2c07bdd89191f6 should allow you to work around this by omitting the surrounding form, using custom attributes to configure the HTTP request instead:

```
<input ... name="query" data-formaction="/search" data-formmethod="post"
    data-scope="self">
```

(Note that `Simplete#load` currently still references a surrounding form, but that's optional and only used to add a "pending" class - not sure it's worth making that configurable as well.)

Please let me know whether this works for you.

**Comment by dasnovum** [comment]
Looks great!

Sometimes it is necessary to have additional parameters.

```
<input ... name="query" data-formaction="/search" data-formmethod="post" data-param-foobar="123"
    data-scope="self">
```

I implemented the following solution:

```
simplete.Simplete.prototype.load = function() { 
  var url = this.field.data("url");
  var query = this.field.val();
  var data = this.field.data();

  var parameter = { 'query' : query };
  $.each(data, function(key, value) 
  {
      if(key.indexOf( "param" ) == 0 ) 
      {
          var key = key.replace( "param", "" ).toLowerCase();
          parameter[ key ] = value;
      }
  });

  var req = $.ajax({
    type: "GET",
    url: url,
    data: parameter,
    dataType: "html"
  });

  req.done(this.open.bind(this));

};
```

**Comment by FND** [comment]
> Sometimes it is necessary to have additional parameters.

Can't you just add those to the URL (i.e. `data-formaction`)?

**Comment by dasnovum** [comment]
Yes you're right this would be a lot easier! :+1:
